create schema if not exists steam;

set search_path to steam;

CREATE TABLE user_account
(
    uid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    date_created DATE NOT NULL,
    games_owned INTEGER DEFAULT 0 -- due to users not acutally needing to have any games
                                  -- owned to have an account on steam
);

CREATE TABLE library
(
    owner_id INTEGER,
    lib INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    games TEXT,
    numbers_of_games INTEGER
    -- FOREIGN KEY (user_id) REFERENCES user_account (uid)
);

CREATE TABLE game -- add plenty of games there, I got names ready for all of that
(
    gid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    user_played INTEGER,
    friends_played INTEGER -- I don't know what name to give to this one
);

CREATE TABLE GameGenres
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre TEXT,
    game_id INTEGER
)

